name: cs491
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - images/logo.png
     - images/cookie.jpg
     - assets/RFDB.db
     - images/gif_cry.gif


# leave comments here:
# 1/13/2020. I made the front page of our app. The buttons don't work yet. -CY
# 1/16/2020. I changed the structure of the project so that the pages of the app are separated into
#    different dart files. The routes.dart file is used to control which pages everything goes to. -CY 
# 1/23/2020. Created a container for search results. -CY
# 1/25/2020. Added a few packages and set some imports. Created a test environment that can be found
#    through the DELIVER button. -CY